services:
  backend:
    image: ghcr.io/osadchii/lang-agent-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/osadchii/lang-agent-frontend:latest
    ports:
      - "4173:80"
    restart: unless-stopped
