services:
  backend:
    image: ghcr.io/osadchii/lang-agent-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/osadchii/lang-agent-frontend:latest
    ports:
      - "4173:80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lang-agent.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/`)"
      - "traefik.http.routers.lang-agent.entrypoints=websecure"
      - "traefik.http.routers.lang-agent.tls.certresolver=myresolver"
      - "traefik.http.services.lang-agent.loadbalancer.server.port=80"
